import Mathlib.SetTheory.Ordinal.Topology
import Counterexamples.Omega1Space

/-! S_ω_1 as a topological space with order topology -/
open Set
open Ordinal
open TopologicalSpace

theorem omega1_order_topology_eq_omega1_space :
  (ω₁ : Ordinal) = ω₁ := by
    rfl

open Ordinal Cardinal

-- Zulip community discussion: https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/The.20space.20S_omega.20is.20first.20countable/with/628988360
theorem firstCountable_omega1 : FirstCountableTopology (Set.Iio ω₁) := by
  constructor
  intro ⟨x, hx⟩
  suffices (nhds x).IsCountablyGenerated by
    rw [nhds_subtype_eq_comap]
    exact Filter.comap.isCountablyGenerated _ _
  by_cases H : IsMin x
  · rw [SuccOrder.nhds_of_isMin H]
    exact Filter.isCountablyGenerated_pure _
  · rw [not_isMin_iff] at H
    have : (nhds x).HasCountableBasis (· < x) fun y => Set.Ioc y x := {
      countable := countable_Iio_of_lt_omega_one hx
      toHasBasis := SuccOrder.hasBasis_nhds_Ioc_of_exists_lt H
    }
    exact this.isCountablyGenerated
