import Mathlib.SetTheory.Ordinal.Topology
import Counterexamples.Omega1Space

/-! S_ω_1 as a topological space with order topology -/
open Set
open Ordinal
open TopologicalSpace

theorem omega1_order_topology_eq_omega1_space :
  (ω₁ : Ordinal) = ω₁ := by
    rfl

open Ordinal Cardinal

-- Zulip community discussion: https://leanprover.zulipchat.com/#narrow/channel/113489-new-members/topic/The.20space.20S_omega.20is.20first.20countable/with/628988360
theorem firstCountable_omega1 : FirstCountableTopology (Set.Iio (Ordinal.omega 1)) := by
  constructor
  intro ⟨x, hx⟩
  suffices (nhds x).IsCountablyGenerated by
    rw [nhds_subtype_eq_comap]
    exact Filter.comap.isCountablyGenerated _ _
  by_cases H : IsMin x
  · rw [SuccOrder.nhds_of_isMin H]
    exact Filter.isCountablyGenerated_pure _
  · rw [not_isMin_iff] at H
    have : (nhds x).HasCountableBasis (· < x) fun y => Set.Ioc y x := {
      countable := countable_Iio_of_lt_omega_one hx
      toHasBasis := SuccOrder.hasBasis_nhds_Ioc_of_exists_lt H
    }
    exact this.isCountablyGenerated


theorem not_secondcountable_omega1 : ¬SecondCountableTopology
  (Set.Iio (Ordinal.omega 1 : Ordinal.{0})) := by
  let SΩ := Set.Iio (Ordinal.omega 1 : Ordinal.{0})
  intro h
  -- let : SecondCountableTopology (SΩ) := h
  -- obtain ⟨B, hB_basis, hB_count⟩ :=
  --   TopologicalSpace.exists_countable_basis (α := SΩ)
  let L : Set SΩ := {x : SΩ | ∃ y < x, Set.Ioo y x = ∅} --(x, x+1) is empty
  have hcount : L.Countable := countable_of_isolated_left'
  have hcard := Cardinal.mk_Iio_ordinal (Ordinal.omega 1 : Ordinal.{0})
  rw [Ordinal.card_omega] at hcard
  have hωlim : Order.IsSuccLimit (ω₁ : Ordinal.{0}) := Cardinal.isSuccLimit_omega 1
  have hωpre : Order.IsSuccPrelimit (ω₁ : Ordinal.{0}) := hωlim.isSuccPrelimit
  let f : SΩ → L := fun x => ⟨
    ⟨x.1 + 1, by exact hωlim.succ_lt x.2⟩, by
      refine ⟨x, ?_, ?_⟩
      · change x.1 < x.1 + 1
        simp only [lt_add_iff_pos_right, Order.lt_one_iff]
      · refine Set.eq_empty_iff_forall_notMem.2 fun z hz => ?_
        have h1 : x.1 < z.1 := hz.1
        have h2 : z.1 < x.1 + 1 := hz.2
        exact absurd (Order.lt_add_one_iff.1 h2) (not_le.2 h1)
      ⟩
  have hf : Function.Injective f := by
    intro x y hxy
    apply Subtype.ext
    rw [Subtype.mk_eq_mk] at hxy
    have hxy' : (↑x : Ordinal) + 1 = (↑y : Ordinal) + 1 := by
        exact congrArg (fun z : SΩ => (z : Ordinal)) hxy
    simp only [Order.add_one_inj] at hxy'
    exact hxy'
  have hL : Countable L := by
    apply Set.Countable.to_subtype
    exact hcount
  have SΩ_countable : Countable SΩ := Function.Injective.countable hf
  have card_SΩ : #SΩ ≤ ℵ₀ := Cardinal.mk_le_aleph0
  rw [hcard] at card_SΩ
  have hlt :
    Cardinal.lift.{1,0} (ℵ₀ : Cardinal.{0}) <
      Cardinal.lift.{1,0} (ℵ_ 1 : Cardinal.{0}) := by
      rw [Cardinal.lift_lt]
      exact Cardinal.aleph0_lt_aleph_one
  rw [Cardinal.lift_aleph0] at hlt
  exact (not_lt_of_ge card_SΩ) hlt

abbrev SΩ : Set Ordinal.{0} := Set.Iio (Ordinal.omega 1)

theorem omega1_space_not_lindelof : ¬LindelofSpace (SΩ) := by
  intro h
  let cover: Set (Set SΩ) := {U : Set SΩ | ∃ x : SΩ, U = Iio x}
  have U_is_open : ∀ U ∈ cover, IsOpen U := by
    intro U hU
    obtain ⟨x, hx⟩ := hU
    rw [hx]
    exact isOpen_Iio
  have hωlim : Order.IsSuccLimit (ω₁ : Ordinal.{0}) := Cardinal.isSuccLimit_omega 1
  have hωpre : Order.IsSuccPrelimit (ω₁ : Ordinal.{0}) := hωlim.isSuccPrelimit
  have hcov : (Set.univ : Set SΩ) ⊆ ⋃ U ∈ cover, U := by
    intro x _
    simp only [mem_iUnion, exists_prop]
    exact ⟨Iio ⟨x.1 + 1, by simpa using hωlim.succ_lt x.2⟩, ⟨_, rfl⟩, by
      change x.1 < x.1 + 1
      simp⟩
  obtain ⟨c, hc_sub, hc_count, hc_cov⟩ :=
    (isLindelof_univ (X := SΩ)).elim_countable_subcover_image
      (b := cover) (c := id) U_is_open hcov
  have hex : ∀ U : ↥c, ∃ x : SΩ, U = Iio x := by
    intro U
    exact hc_sub U.property
  choose endpoint hendpoint using hex
  let : Countable ↥c := hc_count.to_subtype
  let σ : Ordinal := ⨆ U : ↥c, (endpoint U).val
  have hσ : σ < ω₁ :=
    Ordinal.iSup_lt_omega_one
      (fun U : ↥c => (endpoint U).property)
  let p : SΩ := ⟨σ, hσ⟩
  have hp : p ∈ ⋃ U ∈ c, U := hc_cov (Set.mem_univ p)
  simp only [Set.mem_iUnion] at hp
  obtain ⟨U, hUc, hpU⟩ := hp
  have hU : U = Iio (endpoint ⟨U, hUc⟩) := hendpoint ⟨U, hUc⟩
  rw [hU] at hpU
  change σ < (endpoint ⟨U, hUc⟩).val at hpU
  have hle : (endpoint ⟨U, hUc⟩).val ≤ σ := by
    dsimp only [σ]
    exact Ordinal.le_iSup
      (fun V : ↥c => (endpoint V).val) ⟨U, hUc⟩
  exact not_lt_of_ge hle hpU


theorem omega1_space_not_separable : ¬SeparableSpace (SΩ) := by
  intro h
  obtain ⟨s, hs_dense, hs_count⟩ := h
  sorry
